"""Add course field to StudySession

Revision ID: b6546207be3a
Revises: e6c1284e5fe3
Create Date: 2024-09-11 00:26:27.239050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6546207be3a'
down_revision = 'e6c1284e5fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=128), nullable=False))
        batch_op.drop_column('location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
        batch_op.drop_column('course')
    # ### end Alembic commands ###
